apiVersion: v1
kind: Pod
metadata:
  name: debug-pod
  labels:
    app: debug-monitoring
spec:
  volumes:
    - name: learning-transport-data
      persistentVolumeClaim:
        claimName: learning-transport-data
  containers:  
    - name: servicecontrol-monitoring-debug
      image: particular/servicecontrol-monitoring:latest
      env:
        - name: TRANSPORTTYPE
          value: LearningTransport
        - name: CONNECTIONSTRING
          value: /transport
      volumeMounts:
        - mountPath: /transport
          name: learning-transport-data
      command: ["sh", "-c", "sleep 840000s"]