apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: servicepulse-ingress
  labels:
    app: particular-servicepulse
spec:
  defaultBackend:
    service:
      name: servicepulse-service
      port:
        number: 80
---
apiVersion: v1
kind: Service
metadata:
  name: servicepulse-service
  labels:
    app: particular-servicepulse
spec:
  ports:
  - port: 80
    name: servicepulse-pod
  clusterIP: None
  selector:
    app: particular-servicepulse
---
apiVersion: v1
kind: Pod
metadata:
  name: servicepulse-pod
  labels: 
    app: particular-servicepulse
spec:
  containers:  
  - name: servicepulse
    image: particular/servicepulse:latest
    env:
      - name: SERVICECONTROL_URL
        value: "http://servicecontrol-error-service:33333/api/"
      - name: MONITORING_URLS
        value: "['http://servicecontrol-monitoring-service:33633/']"