apiVersion: v1
kind: Service
metadata:
  name: servicecontrol-audit-service
  labels:
    app: particular-servicecontrol-audit
spec:
  ports:
  - port: 44444
    name: servicecontrol-audit-statefulset
  clusterIP: None
  selector:
    app: particular-servicecontrol-audit
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: audit-db-files
  labels:
    type: local
spec:
  storageClassName: audit-db-local
  persistentVolumeReclaimPolicy: Retain
  accessModes: [ "ReadWriteOnce"]
  capacity:
    storage: 500M
  hostPath:
    type: DirectoryOrCreate
    path: "/tmp/audit-db-files"
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: servicecontrol-audit-statefulset
spec:
  serviceName: servicecontrol-audit-service
  replicas: 1
  selector:
    matchLabels:
      app: particular-servicecontrol-audit
  updateStrategy:
    type: OnDelete
  persistentVolumeClaimRetentionPolicy:
    whenDeleted: Retain
  volumeClaimTemplates:
  - metadata:
      name: audit-db-data
    spec:
      storageClassName: audit-db-local
      accessModes: [ "ReadWriteOnce"]
      resources:
        requests:
          storage: 500M
  template:
    metadata:
      labels:
        app: particular-servicecontrol-audit
    spec:
      volumes:
        - name: learning-transport-data
          persistentVolumeClaim:
            claimName: learning-transport-data
      containers:
        - name: servicecontrol-audit
          image: particular/servicecontrol-audit:latest
          env:
            - name: TRANSPORTTYPE
              value: "LearningTransport"
            - name: CONNECTIONSTRING
              value: "/transport"
            - name: RAVENDB_CONNECTIONSTRING
              value: "http://localhost:8080"
          volumeMounts:
            - mountPath: /transport
              name: learning-transport-data
      initContainers:
        - name: servicecontrol-audit-db
          image: particular/servicecontrol-ravendb:latest
          restartPolicy: Always
          volumeMounts:
          - name: audit-db-data
            mountPath: /opt/RavenDB/Server/RavenData
        - name: wait-for-ravendb
          image: curlimages/curl:latest
          command: ['-o', 'ping.json', 'http://localhost:8080/admin/debug/node/ping']
        - name: ensure-transport-can-write
          image: busybox:latest
          command: ['chmod', 'a+w', '/transport']
          volumeMounts:
            - mountPath: /transport
              name: learning-transport-data
        - name: init-servicecontrol-audit
          image: particular/servicecontrol-audit:latest
          args: ['--setup']
          env:
            - name: TRANSPORTTYPE
              value: "LearningTransport"
            - name: CONNECTIONSTRING
              value: "/transport"
            - name: RAVENDB_CONNECTIONSTRING
              value: "http://localhost:8080"
          volumeMounts:
            - mountPath: /transport
              name: learning-transport-data