apiVersion: v1
kind: PersistentVolume
metadata:
  name: learning-transport-data
  labels:
    type: local
spec:
  storageClassName: transport-files
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    type: DirectoryOrCreate
    path: "/tmp/learning-transport-data"
  capacity:
    storage: 100M
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: learning-transport-data
spec:
  storageClassName: transport-files
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100M