apiVersion: v1
kind: Service
metadata:
  name: servicecontrol-error-service
  labels:
    app: particular-servicecontrol-error
spec:
  ports:
  - port: 33333
    name: servicecontrol-error-statefulset
  clusterIP: None
  selector:
    app: particular-servicecontrol-error
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: error-db-files
  labels:
    type: local
spec:
  storageClassName: error-db-local
  persistentVolumeReclaimPolicy: Retain
  accessModes: [ "ReadWriteOnce"]
  capacity:
    storage: 500M
  hostPath:
    type: DirectoryOrCreate
    path: "/tmp/error-db-files"
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: servicecontrol-error-statefulset
spec:
  serviceName: servicecontrol-error-service
  replicas: 1
  selector:
    matchLabels:
      app: particular-servicecontrol-error
  updateStrategy:
    type: OnDelete
  persistentVolumeClaimRetentionPolicy:
    whenDeleted: Retain
  volumeClaimTemplates:
  - metadata:
      name: error-db-data
    spec:
      storageClassName: error-db-local
      accessModes: [ "ReadWriteOnce"]
      resources:
        requests:
          storage: 500M
  template:
    metadata:
      labels:
        app: particular-servicecontrol-error
    spec:
      volumes:
        - name: learning-transport-data
          persistentVolumeClaim:
            claimName: learning-transport-data
      containers:
        - name: servicecontrol-error
          image: particular/servicecontrol:latest
          env:
            - name: TRANSPORTTYPE
              valueFrom:
                configMapKeyRef:
                  name: transport-config 
                  key: TRANSPORTTYPE
            - name: CONNECTIONSTRING
              valueFrom:
                configMapKeyRef:
                  name: transport-config 
                  key: CONNECTIONSTRING
            - name: RAVENDB_CONNECTIONSTRING
              value: http://localhost:8080
            - name: SERVICECONTROL_REMOTEINSTANCES
              value: '[{"api_uri":"http://servicecontrol-audit-service:44444/api"}]'
          volumeMounts:
            - mountPath: /transport
              name: learning-transport-data
      initContainers:
        - name: servicecontrol-error-db
          image: particular/servicecontrol-ravendb:latest
          restartPolicy: Always
          volumeMounts:
          - name: error-db-data
            mountPath: /opt/RavenDB/Server/RavenData
        - name: wait-for-ravendb
          image: curlimages/curl:latest
          command: ['curl', '-o', 'ping.json', 'http://localhost:8080/admin/debug/node/ping']
        - name: ensure-transport-can-write
          image: busybox:latest
          command: ['chmod', 'a+w', '/transport']
          volumeMounts:
            - mountPath: /transport
              name: learning-transport-data
        - name: init-servicecontrol-error
          image: particular/servicecontrol:latest
          args: ['--setup']
          env:
            - name: TRANSPORTTYPE
              valueFrom:
                configMapKeyRef:
                  name: transport-config 
                  key: TRANSPORTTYPE
            - name: CONNECTIONSTRING
              valueFrom:
                configMapKeyRef:
                  name: transport-config 
                  key: CONNECTIONSTRING
            - name: RAVENDB_CONNECTIONSTRING
              value: http://localhost:8080
          volumeMounts:
            - mountPath: /transport
              name: learning-transport-data