apiVersion: v1
kind: Service
metadata:
  name: servicecontrol-error-service
spec:
  selector:
    app.kubernetes.io/name: particular-servicecontrol-error
  ports:
  - name: servicecontrol-error-api
    protocol: TCP
    port: 33333
    targetPort: http-web-svc