apiVersion: v1
kind: PersistentVolume
metadata:
  name: audit-db-data
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostpath:
    path: /tmp/audit-db-data